name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust if using a different branch


permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Packages
      run: echo ${{ secrets.KUBE_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/kingshadie/kubernetes-cicd-deployment:latest .

    - name: Push Docker image
      run: docker push ghcr.io/kingshadie/kubernetes-cicd-deployment:latest


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -R

      - name: Set up Kubernetes
        run: |
          # Commands to configure kubectl
          # e.g., configure access to your Kubernetes cluster
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -R

      - name: Set up Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml